// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeAndBilling.Models;

namespace TimeAndBilling.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200213183223_added Time Entry")]
    partial class addedTimeEntry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TimeAndBilling.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("AlternatePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TimeAndBilling.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeAndBilling.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeIDId")
                        .HasColumnType("int");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectIDId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeIDId");

                    b.HasIndex("ProjectIDId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("TimeAndBilling.Models.Employee", b =>
                {
                    b.HasOne("TimeAndBilling.Models.TimeEntry", null)
                        .WithMany("Employees")
                        .HasForeignKey("TimeEntryId");
                });

            modelBuilder.Entity("TimeAndBilling.Models.Project", b =>
                {
                    b.HasOne("TimeAndBilling.Models.TimeEntry", null)
                        .WithMany("Projects")
                        .HasForeignKey("TimeEntryId");
                });

            modelBuilder.Entity("TimeAndBilling.Models.TimeEntry", b =>
                {
                    b.HasOne("TimeAndBilling.Models.Employee", "EmployeeID")
                        .WithMany()
                        .HasForeignKey("EmployeeIDId");

                    b.HasOne("TimeAndBilling.Models.Project", "ProjectID")
                        .WithMany()
                        .HasForeignKey("ProjectIDId");
                });
#pragma warning restore 612, 618
        }
    }
}
